<?php

namespace App\Notifications;

use App\Models\Domain;
use App\Models\DmarcEvent;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class DmarcAlert extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(
        public Domain $domain,
        public DmarcEvent $event
    ) {}

    /**
     * Get the notification's delivery channels.
     */
    public function via($notifiable): array
    {
        $prefs = $notifiable->getNotificationPrefs();
        
        if ($prefs->email_enabled) {
            return ['mail'];
        }

        return [];
    }

    /**
     * Get the mail representation of the notification.
     */
    public function toMail($notifiable): MailMessage
    {
        $severityEmoji = $this->getSeverityEmoji();
        $actionUrl = route('dmarc.show', $this->domain);

        $message = (new MailMessage)
            ->subject("DMARC Alert: {$this->event->type_label} - {$this->domain->domain}")
            ->greeting("DMARC Alert {$severityEmoji}")
            ->line("An event has been detected for your domain **{$this->domain->domain}**:")
            ->line("**{$this->event->title}**");

        if ($this->event->description) {
            $message->line($this->event->description);
        }

        // Add metrics if available
        if ($this->event->previous_rate !== null && $this->event->current_rate !== null) {
            $message->line("**Previous Rate:** {$this->event->previous_rate}%");
            $message->line("**Current Rate:** {$this->event->current_rate}%");
        }

        if ($this->event->volume) {
            $message->line("**Volume:** " . number_format($this->event->volume) . " emails");
        }

        if ($this->event->source_ip) {
            $message->line("**Top Sender:** {$this->event->source_ip}");
        }

        $message->line("**Detected:** {$this->event->created_at->format('M j, Y \a\t g:i A')}");

        // Add guidance based on event type
        $guidance = $this->getGuidance();
        if ($guidance) {
            $message->line('');
            $message->line('**What to do:**');
            $message->line($guidance);
        }

        $message->action('View DMARC Details', $actionUrl)
            ->line('This alert was generated by MXScan\'s DMARC monitoring system.');

        return $message;
    }

    /**
     * Get the array representation of the notification.
     */
    public function toArray($notifiable): array
    {
        return [
            'type' => 'dmarc_alert',
            'event_type' => $this->event->type,
            'domain_id' => $this->domain->id,
            'domain_name' => $this->domain->domain,
            'event_id' => $this->event->id,
            'title' => $this->event->title,
            'severity' => $this->event->severity,
            'source_ip' => $this->event->source_ip,
        ];
    }

    /**
     * Get emoji for severity level.
     */
    protected function getSeverityEmoji(): string
    {
        return match ($this->event->severity) {
            'critical' => '🚨',
            'warning' => '⚠️',
            'info' => 'ℹ️',
            default => '📋'
        };
    }

    /**
     * Get guidance text based on event type.
     */
    protected function getGuidance(): ?string
    {
        return match ($this->event->type) {
            DmarcEvent::TYPE_NEW_SENDER => 'Review this sender to determine if it\'s a legitimate service (like a new email marketing platform) or a potential spoofing attempt. If legitimate, ensure proper SPF/DKIM configuration.',
            
            DmarcEvent::TYPE_FAIL_SPIKE, DmarcEvent::TYPE_ALIGNMENT_DROP => 'A sudden drop in authentication pass rates may indicate a configuration change, a new unauthorized sender, or a technical issue. Review recent changes to your email infrastructure.',
            
            DmarcEvent::TYPE_DKIM_FAIL_SPIKE => 'DKIM failures often indicate signing issues. Check that your sending services are properly configured with valid DKIM keys and that DNS records are correct.',
            
            DmarcEvent::TYPE_SPF_FAIL_SPIKE => 'SPF failures indicate emails are being sent from IPs not authorized in your SPF record. Review your SPF record and ensure all legitimate sending services are included.',
            
            DmarcEvent::TYPE_POLICY_CHANGE => 'Your DMARC policy has changed. Ensure this was intentional and monitor the impact on email delivery.',
            
            default => null,
        };
    }
}
