@php
    $key = $row['key'] ?? '';
    $detail = $row['detail'] ?? [];
    $solution = $row['remediation'] ?? [];
    $score = $row['score'] ?? [];
    $severityLabel = match ($row['severity'] ?? '') {
        'danger' => 'high',
        'warning' => 'medium',
        'optional' => 'optional',
        default => 'low',
    };
@endphp

<div class="mx-tech-remediation-layout">
    <div class="mx-tech-remediation-context">
        <x-report.issue-panel
            :title="$row['label'] . ' ' . strtolower($row['badgeLabel'] ?? 'needs attention')"
            :severity="$severityLabel"
            :impact="$row['help']['text'] ?? $row['result']"
            :earned="$score['earned'] ?? null"
            :possible="$score['possible'] ?? null"
            :lost-points="$row['lostPoints'] ?? null"
            :optional="$row['optional'] ?? false"
        />

        <x-report.evidence-panel>
            @if($key === 'spf')
                <p>No TXT record beginning with <code>v=spf1</code> was found for {{ $domain->domain }}.</p>
                @foreach($detail['detectedMailServers'] ?? [] as $server)
                    <div class="mx-evidence-record">
                        <strong>Detected inbound mail server</strong>
                        <code>{{ $server['hostname'] }}</code>
                        @foreach($server['ipv4'] as $ip)<code>IPv4: {{ $ip }}</code>@endforeach
                        @foreach($server['ipv6'] as $ip)<code>IPv6: {{ $ip }}</code>@endforeach
                    </div>
                @endforeach
            @elseif(in_array($key, ['dmarc', 'dmarc_reports'], true))
                <p>{{ $row['result'] }}</p>
                <div class="mx-evidence-record">
                    <strong>Current DMARC value</strong>
                    <code>{{ $solution['current_value'] ?: 'No DMARC record detected' }}</code>
                </div>
                <strong>Current rua destinations</strong>
                @forelse($solution['current_rua'] ?? [] as $destination)
                    <code>{{ $destination }}</code>
                @empty
                    <p>No aggregate report destination was detected.</p>
                @endforelse
            @elseif($key === 'mtasts')
                <p>{{ $row['result'] }}</p>
                <div class="mx-evidence-record">
                    <strong>Policy probe</strong>
                    <code>{{ $solution['policy_url'] ?? '' }}</code>
                </div>
                @foreach(data_get($solution, 'analysis.errors', []) as $error)
                    <p>{{ $error['message'] ?? '' }}</p>
                @endforeach
            @elseif($key === 'tlsrpt')
                <p>{{ $row['result'] }}</p>
                @foreach(data_get($solution, 'analysis.reporting.destinations', []) as $destination)
                    <code>{{ $destination['normalized_uri'] ?? $destination['raw_uri'] ?? '' }}</code>
                @endforeach
            @elseif($key === 'dkim')
                <p>MXScan checked known DKIM selectors. No valid public key was detected.</p>
                <p>A DKIM public key cannot be invented safely; it must be generated by the sending provider.</p>
            @elseif($key === 'ssl')
                @foreach($solution['endpoints'] ?? [] as $endpoint)
                    <article class="mx-certificate-evidence">
                        <strong>{{ $endpoint['hostname'] ?? 'Unknown endpoint' }}:{{ $endpoint['port'] ?? 443 }}</strong>
                        <dl>
                            <div><dt>Requested hostname</dt><dd>{{ $endpoint['hostname'] ?? '—' }}</dd></div>
                            <div><dt>Certificate CN</dt><dd>{{ is_array($endpoint['subject'] ?? null) ? ($endpoint['subject']['common_name'] ?? '—') : ($endpoint['subject'] ?? '—') }}</dd></div>
                            <div><dt>SAN values</dt><dd>{{ implode(', ', $endpoint['san_dns'] ?? []) ?: '—' }}</dd></div>
                            <div><dt>Verification</dt><dd>{{ $endpoint['verification_state'] ?? 'unknown' }}</dd></div>
                            <div><dt>Exact mismatch</dt><dd>{{ $endpoint['hostname_mismatch_reason'] ?? '—' }}</dd></div>
                            <div><dt>Issuer</dt><dd>{{ is_array($endpoint['issuer'] ?? null) ? ($endpoint['issuer']['common_name'] ?? '—') : ($endpoint['issuer'] ?? '—') }}</dd></div>
                        </dl>
                    </article>
                @endforeach
            @elseif($key === 'mx')
                @foreach($detail['rows'] ?? [] as $mxRows)
                    <div class="mx-evidence-record">
                        @foreach($mxRows as $field)
                            <span><strong>{{ $field['label'] }}:</strong> {{ $field['value'] }}</span>
                        @endforeach
                    </div>
                @endforeach
            @else
                <p>{{ $row['result'] }}</p>
                @if(!empty($detail['value']))<code>{{ $detail['value'] }}</code>@endif
            @endif
        </x-report.evidence-panel>
    </div>

    @if(!($row['optional'] ?? false))
        <x-report.solution-panel>
            @if($key === 'spf')
                @include('scans.partials.technical-checks._spf-solution', compact('row', 'technicalRemediation'))
            @elseif(in_array($key, ['dmarc', 'dmarc_reports'], true))
                <h4>Publish the corrected DMARC record</h4>
                <p>MXScan reporting address: <strong>{{ ($solution['mxscan_present'] ?? false) ? 'Present' : 'Missing' }}</strong></p>
                <x-report.dns-solution-record
                    :type="$solution['type'] ?? 'TXT'"
                    :host="$solution['host'] ?? '_dmarc'"
                    :value="$solution['corrected_value'] ?? ''"
                    :ttl="$solution['ttl'] ?? 'Auto'"
                    title="Corrected DMARC record"
                />
                @if(!empty($solution['external_authorization_hosts']))
                    <div class="mx-tech-callout">
                        <strong>External destination authorization required</strong>
                        <p>The destination domain must publish authorization for:</p>
                        @foreach($solution['external_authorization_hosts'] as $host)<code>{{ $host }}</code>@endforeach
                    </div>
                @endif
                <x-report.dns-provider-instructions :providers="$technicalRemediation['dns_providers'] ?? []" :selected="$technicalRemediation['dns_provider'] ?? null" />
                <x-report.rescan-button />
            @elseif($key === 'mtasts')
                <h4>Publish the DNS record and policy file</h4>
                <x-report.dns-solution-record
                    :type="$solution['type'] ?? 'TXT'"
                    :host="$solution['host'] ?? '_mta-sts'"
                    :value="$solution['value'] ?? ''"
                    :ttl="$solution['ttl'] ?? 'Auto'"
                    title="MTA-STS DNS record"
                />
                <div class="mx-policy-file">
                    <strong>Policy hostname</strong><code>{{ $solution['policy_hostname'] ?? '' }}</code>
                    <strong>Required file URL</strong><code>{{ $solution['policy_url'] ?? '' }}</code>
                    <strong>Suggested policy template</strong><pre>{{ $solution['policy'] ?? '' }}</pre>
                </div>
                <div class="mx-tech-action-row">
                    <x-report.copy-button :value="$solution['policy'] ?? ''" label="Copy policy" class="mx-btn-secondary !static" />
                    <a href="{{ route('domains.remediation.mta-sts.policy', [$domain, $scan]) }}" class="mx-btn mx-btn-secondary">Download policy file</a>
                    <button type="button" class="mx-btn mx-btn-ghost" @click="dnsProvider = 'other'">View web-server instructions</button>
                </div>
                <x-report.dns-provider-instructions :providers="$technicalRemediation['dns_providers'] ?? []" :selected="$technicalRemediation['dns_provider'] ?? null" />
                <x-report.rescan-button />
            @elseif($key === 'tlsrpt')
                <h4>Create this TLS-RPT TXT record</h4>
                <x-report.dns-solution-record
                    :type="$solution['type'] ?? 'TXT'"
                    :host="$solution['host'] ?? '_smtp._tls'"
                    :value="$solution['value'] ?? ''"
                    :ttl="$solution['ttl'] ?? 'Auto'"
                    title="Recommended TLS-RPT record"
                />
                <x-report.dns-provider-instructions :providers="$technicalRemediation['dns_providers'] ?? []" :selected="$technicalRemediation['dns_provider'] ?? null" />
                <x-report.rescan-button />
            @elseif($key === 'dkim')
                <h4>Enable DKIM in the sending provider</h4>
                <p>Select the service that sends mail. Generate the key there, then publish the DNS records it provides.</p>
                @foreach($technicalRemediation['sender_providers'] ?? [] as $provider)
                    @if(!empty($provider['dkim_steps']))
                        <details class="mx-provider-setup">
                            <summary>{{ $provider['name'] }} DKIM setup</summary>
                            <ol>@foreach($provider['dkim_steps'] as $step)<li>{{ $step }}</li>@endforeach</ol>
                        </details>
                    @endif
                @endforeach
                <details class="mx-provider-setup"><summary>cPanel DKIM setup</summary><ol><li>Open Email Deliverability.</li><li>Select the domain.</li><li>Use Repair to publish the generated DKIM record.</li></ol></details>
                <details class="mx-provider-setup"><summary>Custom mail server setup</summary><ol><li>Generate a private/public DKIM key pair on the mail server.</li><li>Configure signing with a selector.</li><li>Publish the public key at selector._domainkey.</li></ol></details>
                <x-report.rescan-button />
            @elseif($key === 'ssl')
                <h4>Replace or renew the affected certificate</h4>
                <ol class="mx-solution-steps">
                    <li>Request a certificate containing every affected hostname in its SAN list.</li>
                    <li>Install the full certificate chain on the affected HTTPS or SMTP endpoint.</li>
                    <li>Reload the web or mail service and verify SNI/hostname configuration.</li>
                </ol>
                <x-report.rescan-button />
            @else
                <h4>Fix this configuration</h4>
                <p>{{ $row['help']['fix'] ?? 'Apply the required configuration shown in the evidence, then scan the domain again.' }}</p>
                <x-report.rescan-button />
            @endif
        </x-report.solution-panel>
    @endif
</div>
