<?php

return [
    'providers' => [
        // Spamhaus Family (Most Critical - Keep ZEN only as it includes SBL+XBL+PBL)
        'spamhaus_zen' => [
            'name' => 'Spamhaus ZEN',
            'host' => 'zen.spamhaus.org',
            'site' => 'https://www.spamhaus.org/zen/',
            'delist_url' => 'https://check.spamhaus.org/',
            'contact_email' => null,
            'requires_evidence' => true,
            'enabled' => true,
            'instructions' => [
                'ZEN is a combination of SBL, XBL, and PBL.',
                'Use the Spamhaus lookup tool to identify which specific list contains your IP.',
                'Follow the removal process for the specific list (SBL, XBL, or PBL).',
            ],
        ],
        'spamhaus_sbl' => [
            'name' => 'Spamhaus SBL',
            'host' => 'sbl.spamhaus.org',
            'site' => 'https://www.spamhaus.org/sbl/',
            'delist_url' => 'https://check.spamhaus.org/',
            'contact_email' => null,
            'requires_evidence' => true,
            'enabled' => false, // Disabled - covered by ZEN
            'instructions' => [
                'Go to the Spamhaus SBL lookup and enter your IP/domain.',
                'Open the record and follow the "Removal" process.',
                'Explain the root cause (e.g., compromised host, misconfigured server) and remediation.',
                'Provide logs/screenshots if requested.',
            ],
        ],
        'spamhaus_xbl' => [
            'name' => 'Spamhaus XBL',
            'host' => 'xbl.spamhaus.org',
            'site' => 'https://www.spamhaus.org/xbl/',
            'delist_url' => 'https://check.spamhaus.org/',
            'contact_email' => null,
            'requires_evidence' => true,
            'enabled' => false, // Disabled - covered by ZEN
            'instructions' => [
                'Go to the Spamhaus XBL lookup and enter your IP.',
                'If listed, follow the removal instructions provided.',
                'Ensure all compromised machines are cleaned and secured.',
                'Provide evidence of remediation if requested.',
            ],
        ],
        'spamhaus_pbl' => [
            'name' => 'Spamhaus PBL',
            'host' => 'pbl.spamhaus.org',
            'site' => 'https://www.spamhaus.org/pbl/',
            'delist_url' => 'https://www.spamhaus.org/pbl/removal/',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => false, // Disabled - covered by ZEN
            'instructions' => [
                'PBL listings are for dynamic/residential IPs that should not send email.',
                'If you have a legitimate mail server, request removal via the PBL removal form.',
                'Provide justification for why this IP should send email directly.',
            ],
        ],
        
        // Major RBL Providers (Top Tier)
        'barracuda' => [
            'name' => 'Barracuda',
            'host' => 'b.barracudacentral.org',
            'site' => 'https://www.barracudanetworks.com/',
            'delist_url' => 'https://www.barracudacentral.org/rbl/removal-request',
            'contact_email' => null,
            'requires_evidence' => true,
            'enabled' => true,
            'instructions' => [
                'Open the Barracuda BRBL delisting page.',
                'Provide your IP and a brief explanation of the fix.',
                'Submit and wait for confirmation. Re-check in a few hours.',
            ],
        ],
        'sorbs' => [
            'name' => 'SORBS',
            'host' => 'dnsbl.sorbs.net',
            'site' => 'http://www.sorbs.net/',
            'delist_url' => 'http://www.sorbs.net/delisting/',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => true,
            'instructions' => [
                'Visit the SORBS delisting page and enter your IP address.',
                'Follow the automated delisting process.',
                'Some SORBS lists require manual review - check the specific list requirements.',
            ],
        ],
        // SpamCop and CBL (Critical)
        'spamcop' => [
            'name' => 'SpamCop',
            'host' => 'bl.spamcop.net',
            'site' => 'https://www.spamcop.net/',
            'delist_url' => 'https://www.spamcop.net/bl.shtml',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => true,
            'instructions' => [
                'SpamCop listings are usually temporary and auto-expire.',
                'Check the SpamCop blacklist page for your IP status.',
                'Most listings resolve automatically within 24-48 hours.',
            ],
        ],
        'cbl' => [
            'name' => 'Composite Blocking List',
            'host' => 'cbl.abuseat.org',
            'site' => 'https://cbl.abuseat.org/',
            'delist_url' => 'https://cbl.abuseat.org/lookup.cgi',
            'contact_email' => null,
            'requires_evidence' => true,
            'enabled' => true,
            'instructions' => [
                'Use the CBL lookup tool to check your IP status.',
                'If listed, follow the removal instructions provided.',
                'Ensure all compromised machines are cleaned before requesting removal.',
            ],
        ],
        'dronebl' => [
            'name' => 'DroneBL',
            'host' => 'dnsbl.dronebl.org',
            'site' => 'https://dronebl.org/',
            'delist_url' => 'https://dronebl.org/lookup',
            'contact_email' => null,
            'requires_evidence' => true,
            'enabled' => true,
            'instructions' => [
                'Use the DroneBL lookup tool to check your IP status.',
                'If listed, follow the removal process provided.',
                'Ensure all compromised systems are secured.',
            ],
        ],
        
        // Domain-based RBLs (Disabled - less critical for IP checks)
        'surbl' => [
            'name' => 'SURBL',
            'host' => 'multi.surbl.org',
            'site' => 'http://www.surbl.org/',
            'delist_url' => 'http://www.surbl.org/surbl-analysis',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => false,
            'instructions' => [
                'Use the SURBL analysis tool to check your domain status.',
                'If listed, follow the removal instructions provided.',
                'Ensure all malicious content has been removed from your domain.',
            ],
        ],
        'uribl' => [
            'name' => 'URIBL',
            'host' => 'multi.uribl.com',
            'site' => 'https://www.uribl.com/',
            'delist_url' => 'https://admin.uribl.com/',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => false,
            'instructions' => [
                'Login/register at URIBL admin portal and request removal.',
                'If listed due to redirectors or compromised pages, include cleanup details.',
            ],
        ],
        
        // Secondary RBLs (Disabled for performance)
        'psbl' => [
            'name' => 'Passive Spam Block List',
            'host' => 'psbl.surriel.com',
            'site' => 'https://psbl.surriel.com/',
            'delist_url' => 'https://psbl.surriel.com/',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => false,
            'instructions' => [
                'Visit the PSBL website and use their removal form.',
                'PSBL listings are for IPs that should not be sending email directly.',
                'Ensure your mail server configuration is correct before requesting removal.',
            ],
        ],
        'dnsrbl' => [
            'name' => 'DNS RBL',
            'host' => 'blackholes.five-ten-sg.com',
            'site' => 'http://www.five-ten-sg.com/',
            'delist_url' => 'http://www.five-ten-sg.com/blackhole.php',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => false,
            'instructions' => [
                'Visit the Five-Ten-SG blackhole removal page.',
                'Enter your IP address and follow the removal process.',
            ],
        ],
        'mailspike' => [
            'name' => 'Mailspike',
            'host' => 'bl.mailspike.net',
            'site' => 'https://mailspike.net/',
            'delist_url' => 'https://mailspike.net/anubis/lookup.html',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => false,
            'instructions' => [
                'Use the Mailspike Anubis lookup tool to check your IP.',
                'Follow the delisting instructions if your IP is listed.',
            ],
        ],
        'invaluement' => [
            'name' => 'Invaluement',
            'host' => 'ivmSIP.invaluement.com',
            'site' => 'http://www.invaluement.com/',
            'delist_url' => 'http://www.invaluement.com/removal/',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => false,
            'instructions' => [
                'Visit the Invaluement removal page.',
                'Submit your IP for delisting review.',
            ],
        ],
        'blocklist_de' => [
            'name' => 'Blocklist.de',
            'host' => 'bl.blocklist.de',
            'site' => 'https://www.blocklist.de/',
            'delist_url' => 'https://www.blocklist.de/en/delist.html',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => false,
            'instructions' => [
                'Use the Blocklist.de delisting form.',
                'Provide your IP and reason for delisting.',
            ],
        ],
        'njabl' => [
            'name' => 'NJABL',
            'host' => 'dnsbl.njabl.org',
            'site' => 'http://njabl.org/',
            'delist_url' => 'http://njabl.org/',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => false,
            'instructions' => [
                'Visit the NJABL website for delisting information.',
                'Note: NJABL may no longer be actively maintained.',
            ],
        ],
        'ahbl' => [
            'name' => 'AHBL',
            'host' => 'dnsbl.ahbl.org',
            'site' => 'https://www.ahbl.org/',
            'delist_url' => 'https://www.ahbl.org/lktool',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => false,
            'instructions' => [
                'Submit delist via the official lookup/delist tool.',
            ],
        ],
        'manitu' => [
            'name' => 'Manitu',
            'host' => 'ix.dnsbl.manitu.net',
            'site' => 'http://www.dnsbl.manitu.net/',
            'delist_url' => 'http://www.dnsbl.manitu.net/',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => false,
            'instructions' => [
                'Visit the Manitu DNSBL website.',
                'Follow their delisting procedure.',
            ],
        ],
        'spamrats' => [
            'name' => 'SpamRATS',
            'host' => 'noptr.spamrats.com',
            'site' => 'http://www.spamrats.com/',
            'delist_url' => 'http://www.spamrats.com/removal.php',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => false,
            'instructions' => [
                'Use the SpamRATS removal form.',
                'Provide your IP and justification for removal.',
            ],
        ],
        'backscatterer' => [
            'name' => 'Backscatterer',
            'host' => 'ips.backscatterer.org',
            'site' => 'http://www.backscatterer.org/',
            'delist_url' => 'http://www.backscatterer.org/?target=test',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => false,
            'instructions' => [
                'Visit the Backscatterer website and use their test tool.',
                'Follow the delisting instructions provided.',
            ],
        ],
        'truncate' => [
            'name' => 'Truncate',
            'host' => 'truncate.gbudb.net',
            'site' => 'http://www.gbudb.com/',
            'delist_url' => 'http://www.gbudb.com/',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => false,
            'instructions' => [
                'Visit the GBUdb website for delisting information.',
                'Follow their removal procedure.',
            ],
        ],
        'dcc' => [
            'name' => 'DCC',
            'host' => 'blacklist.woody.ch',
            'site' => 'http://www.dcc-servers.net/dcc/',
            'delist_url' => 'http://www.dcc-servers.net/dcc/',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => false,
            'instructions' => [
                'Visit the DCC servers website.',
                'Follow their delisting procedure.',
            ],
        ],
        'rbl_jp' => [
            'name' => 'RBL.JP',
            'host' => 'all.rbl.jp',
            'site' => 'http://www.rbl.jp/',
            'delist_url' => 'http://www.rbl.jp/',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => false,
            'instructions' => [
                'Visit the RBL.JP website.',
                'Follow their delisting procedure (may be in Japanese).',
            ],
        ],
    ],
    'settings' => [
        'clean_reputation_bonus' => 10,
        'score_penalty_per_listing' => 5,
        'max_score_penalty' => 30,
    ],
];