<?php

/**
 * DNSBL provider registry — sole runtime provider source for the native blacklist module.
 *
 * Providers without verified listing/blocked semantics remain disabled.
 * Score settings removed: blacklist is reputation-only (Option A).
 */
return [
    'query' => [
        'concurrency' => 20,
        'timeout_ms' => 3000,
        'max_retries' => 1,
        'max_queries' => 500,
        'max_duration_ms' => 30000,
    ],

    'providers' => [
        'spamhaus_zen' => [
            'name' => 'Spamhaus ZEN',
            'host' => 'zen.spamhaus.org',
            'zone' => 'zen.spamhaus.org',
            'ipv6_zone' => 'zen.spamhaus.org',
            'site' => 'https://www.spamhaus.org/zen/',
            'delist_url' => 'https://check.spamhaus.org/',
            'contact_email' => null,
            'requires_evidence' => true,
            'enabled' => true,
            'target_types' => ['ipv4', 'ipv6'],
            'interpreter' => 'spamhaus_zen',
            'listing_codes' => [
                '127.0.0.2', '127.0.0.3', '127.0.0.4', '127.0.0.5',
                '127.0.0.6', '127.0.0.7', '127.0.0.8', '127.0.0.9',
                '127.0.0.10', '127.0.0.11',
            ],
            'blocked_codes' => ['127.255.255.254', '127.255.255.255'],
            'rate_limit_codes' => [],
            'nxdomain_means_clean' => true,
            'no_data_means_clean' => true,
            'timeout_ms' => 3000,
            'max_retries' => 1,
            'metadata' => [
                'status' => 'active',
                'commercial_saas' => 'restricted_public_resolver',
                'notes' => 'Blocks queries from open/public resolvers; blocked responses must not be treated as clean.',
            ],
            'instructions' => [
                'ZEN is a combination of SBL, XBL, and PBL.',
                'Use the Spamhaus lookup tool to identify which specific list contains your IP.',
                'Follow the removal process for the specific list (SBL, XBL, or PBL).',
            ],
        ],
        'barracuda' => [
            'name' => 'Barracuda',
            'host' => 'b.barracudacentral.org',
            'zone' => 'b.barracudacentral.org',
            'site' => 'https://www.barracudanetworks.com/',
            'delist_url' => 'https://www.barracudacentral.org/rbl/removal-request',
            'contact_email' => null,
            'requires_evidence' => true,
            'enabled' => true,
            'target_types' => ['ipv4'],
            'interpreter' => 'standard_ipv4',
            'listing_codes' => ['127.0.0.2'],
            'blocked_codes' => [],
            'rate_limit_codes' => [],
            'nxdomain_means_clean' => true,
            'no_data_means_clean' => true,
            'metadata' => ['status' => 'active', 'commercial_saas' => 'permitted'],
            'instructions' => [
                'Open the Barracuda BRBL delisting page.',
                'Provide your IP and a brief explanation of the fix.',
            ],
        ],
        'spamcop' => [
            'name' => 'SpamCop',
            'host' => 'bl.spamcop.net',
            'zone' => 'bl.spamcop.net',
            'site' => 'https://www.spamcop.net/',
            'delist_url' => 'https://www.spamcop.net/bl.shtml',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => true,
            'target_types' => ['ipv4'],
            'interpreter' => 'standard_ipv4',
            'listing_codes' => ['127.0.0.2'],
            'blocked_codes' => [],
            'rate_limit_codes' => [],
            'nxdomain_means_clean' => true,
            'no_data_means_clean' => true,
            'metadata' => ['status' => 'active', 'commercial_saas' => 'permitted'],
            'instructions' => [
                'SpamCop listings are usually temporary and auto-expire.',
            ],
        ],
        'cbl' => [
            'name' => 'Composite Blocking List',
            'host' => 'cbl.abuseat.org',
            'zone' => 'cbl.abuseat.org',
            'site' => 'https://cbl.abuseat.org/',
            'delist_url' => 'https://cbl.abuseat.org/lookup.cgi',
            'contact_email' => null,
            'requires_evidence' => true,
            'enabled' => true,
            'target_types' => ['ipv4'],
            'interpreter' => 'standard_ipv4',
            'listing_codes' => ['127.0.0.2'],
            'blocked_codes' => [],
            'rate_limit_codes' => [],
            'nxdomain_means_clean' => true,
            'no_data_means_clean' => true,
            'metadata' => ['status' => 'active', 'commercial_saas' => 'permitted'],
            'instructions' => [
                'Use the CBL lookup tool to check your IP status.',
            ],
        ],
        'sorbs' => [
            'name' => 'SORBS',
            'host' => 'dnsbl.sorbs.net',
            'zone' => 'dnsbl.sorbs.net',
            'site' => 'http://www.sorbs.net/',
            'delist_url' => 'http://www.sorbs.net/delisting/',
            'contact_email' => null,
            'requires_evidence' => false,
            'enabled' => true,
            'target_types' => ['ipv4'],
            'interpreter' => 'sorbs',
            'listing_codes' => [
                '127.0.0.2', '127.0.0.3', '127.0.0.4', '127.0.0.5',
                '127.0.0.6', '127.0.0.7', '127.0.0.8', '127.0.0.9',
                '127.0.0.10',
            ],
            'blocked_codes' => [],
            'rate_limit_codes' => [],
            'nxdomain_means_clean' => true,
            'no_data_means_clean' => true,
            'metadata' => ['status' => 'active', 'commercial_saas' => 'permitted'],
            'instructions' => [
                'Visit the SORBS delisting page and enter your IP address.',
            ],
        ],
        'dronebl' => [
            'name' => 'DroneBL',
            'host' => 'dnsbl.dronebl.org',
            'zone' => 'dnsbl.dronebl.org',
            'site' => 'https://dronebl.org/',
            'delist_url' => 'https://dronebl.org/lookup',
            'contact_email' => null,
            'requires_evidence' => true,
            'enabled' => true,
            'target_types' => ['ipv4'],
            'interpreter' => 'dronebl',
            'listing_codes' => [
                '127.0.0.2', '127.0.0.3', '127.0.0.5', '127.0.0.6',
                '127.0.0.7', '127.0.0.8', '127.0.0.9', '127.0.0.10',
                '127.0.0.11', '127.0.0.12', '127.0.0.13', '127.0.0.14',
                '127.0.0.15', '127.0.0.16', '127.0.0.17', '127.0.0.18',
                '127.0.0.19', '127.0.0.20',
            ],
            'blocked_codes' => [],
            'rate_limit_codes' => [],
            'nxdomain_means_clean' => true,
            'no_data_means_clean' => true,
            'metadata' => ['status' => 'active', 'commercial_saas' => 'permitted'],
            'instructions' => [
                'Use the DroneBL lookup tool to check your IP status.',
            ],
        ],

        // Disabled — covered by ZEN, domain-based, unverified, or inactive
        'spamhaus_sbl' => ['name' => 'Spamhaus SBL', 'host' => 'sbl.spamhaus.org', 'zone' => 'sbl.spamhaus.org', 'enabled' => false, 'target_types' => ['ipv4'], 'listing_codes' => [], 'blocked_codes' => [], 'delist_url' => 'https://check.spamhaus.org/', 'site' => 'https://www.spamhaus.org/sbl/', 'requires_evidence' => true, 'instructions' => []],
        'spamhaus_xbl' => ['name' => 'Spamhaus XBL', 'host' => 'xbl.spamhaus.org', 'zone' => 'xbl.spamhaus.org', 'enabled' => false, 'target_types' => ['ipv4'], 'listing_codes' => [], 'blocked_codes' => [], 'delist_url' => 'https://check.spamhaus.org/', 'site' => 'https://www.spamhaus.org/xbl/', 'requires_evidence' => true, 'instructions' => []],
        'spamhaus_pbl' => ['name' => 'Spamhaus PBL', 'host' => 'pbl.spamhaus.org', 'zone' => 'pbl.spamhaus.org', 'enabled' => false, 'target_types' => ['ipv4'], 'listing_codes' => [], 'blocked_codes' => [], 'delist_url' => 'https://www.spamhaus.org/pbl/removal/', 'site' => 'https://www.spamhaus.org/pbl/', 'requires_evidence' => false, 'instructions' => []],
        'surbl' => ['name' => 'SURBL', 'host' => 'multi.surbl.org', 'zone' => 'multi.surbl.org', 'enabled' => false, 'target_types' => ['domain'], 'listing_codes' => [], 'blocked_codes' => [], 'delist_url' => 'http://www.surbl.org/surbl-analysis', 'site' => 'http://www.surbl.org/', 'requires_evidence' => false, 'instructions' => []],
        'uribl' => ['name' => 'URIBL', 'host' => 'multi.uribl.com', 'zone' => 'multi.uribl.com', 'enabled' => false, 'target_types' => ['domain'], 'listing_codes' => [], 'blocked_codes' => [], 'delist_url' => 'https://admin.uribl.com/', 'site' => 'https://www.uribl.com/', 'requires_evidence' => false, 'instructions' => []],
        'psbl' => ['name' => 'Passive Spam Block List', 'host' => 'psbl.surriel.com', 'zone' => 'psbl.surriel.com', 'enabled' => false, 'target_types' => ['ipv4'], 'listing_codes' => [], 'blocked_codes' => [], 'delist_url' => 'https://psbl.surriel.com/', 'site' => 'https://psbl.surriel.com/', 'requires_evidence' => false, 'instructions' => []],
        'dnsrbl' => ['name' => 'DNS RBL', 'host' => 'blackholes.five-ten-sg.com', 'zone' => 'blackholes.five-ten-sg.com', 'enabled' => false, 'target_types' => ['ipv4'], 'listing_codes' => [], 'blocked_codes' => [], 'delist_url' => 'http://www.five-ten-sg.com/blackhole.php', 'site' => 'http://www.five-ten-sg.com/', 'requires_evidence' => false, 'instructions' => []],
        'mailspike' => ['name' => 'Mailspike', 'host' => 'bl.mailspike.net', 'zone' => 'bl.mailspike.net', 'enabled' => false, 'target_types' => ['ipv4'], 'listing_codes' => [], 'blocked_codes' => [], 'delist_url' => 'https://mailspike.net/anubis/lookup.html', 'site' => 'https://mailspike.net/', 'requires_evidence' => false, 'instructions' => []],
        'invaluement' => ['name' => 'Invaluement', 'host' => 'ivmSIP.invaluement.com', 'zone' => 'ivmSIP.invaluement.com', 'enabled' => false, 'target_types' => ['ipv4'], 'listing_codes' => [], 'blocked_codes' => [], 'delist_url' => 'http://www.invaluement.com/removal/', 'site' => 'http://www.invaluement.com/', 'requires_evidence' => false, 'instructions' => []],
        'blocklist_de' => ['name' => 'Blocklist.de', 'host' => 'bl.blocklist.de', 'zone' => 'bl.blocklist.de', 'enabled' => false, 'target_types' => ['ipv4'], 'listing_codes' => [], 'blocked_codes' => [], 'delist_url' => 'https://www.blocklist.de/en/delist.html', 'site' => 'https://www.blocklist.de/', 'requires_evidence' => false, 'instructions' => []],
        'manitu' => ['name' => 'Manitu', 'host' => 'ix.dnsbl.manitu.net', 'zone' => 'ix.dnsbl.manitu.net', 'enabled' => false, 'target_types' => ['ipv4'], 'listing_codes' => [], 'blocked_codes' => [], 'delist_url' => 'http://www.dnsbl.manitu.net/', 'site' => 'http://www.dnsbl.manitu.net/', 'requires_evidence' => false, 'instructions' => []],
        'spamrats' => ['name' => 'SpamRATS', 'host' => 'noptr.spamrats.com', 'zone' => 'noptr.spamrats.com', 'enabled' => false, 'target_types' => ['ipv4'], 'listing_codes' => [], 'blocked_codes' => [], 'delist_url' => 'http://www.spamrats.com/removal.php', 'site' => 'http://www.spamrats.com/', 'requires_evidence' => false, 'instructions' => []],
        'backscatterer' => ['name' => 'Backscatterer', 'host' => 'ips.backscatterer.org', 'zone' => 'ips.backscatterer.org', 'enabled' => false, 'target_types' => ['ipv4'], 'listing_codes' => [], 'blocked_codes' => [], 'delist_url' => 'http://www.backscatterer.org/?target=test', 'site' => 'http://www.backscatterer.org/', 'requires_evidence' => false, 'instructions' => []],
        'truncate' => ['name' => 'Truncate', 'host' => 'truncate.gbudb.net', 'zone' => 'truncate.gbudb.net', 'enabled' => false, 'target_types' => ['ipv4'], 'listing_codes' => [], 'blocked_codes' => [], 'delist_url' => 'http://www.gbudb.com/', 'site' => 'http://www.gbudb.com/', 'requires_evidence' => false, 'instructions' => []],
        'rbl_jp' => ['name' => 'RBL.JP', 'host' => 'all.rbl.jp', 'zone' => 'all.rbl.jp', 'enabled' => false, 'target_types' => ['ipv4'], 'listing_codes' => [], 'blocked_codes' => [], 'delist_url' => 'http://www.rbl.jp/', 'site' => 'http://www.rbl.jp/', 'requires_evidence' => false, 'instructions' => []],
    ],
];
