<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MXScan Weekly Report</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #374151;
            margin: 0;
            padding: 20px;
            background-color: #f9fafb;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
        }
        .header {
            background: linear-gradient(135deg, #3b82f6, #1d4ed8);
            color: white;
            padding: 30px;
            text-align: center;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            font-weight: 600;
        }
        .header p {
            margin: 8px 0 0 0;
            opacity: 0.9;
        }
        .content {
            padding: 30px;
        }
        .summary-box {
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            padding: 20px;
            margin: 20px 0;
        }
        .summary-box h3 {
            margin: 0 0 15px 0;
            color: #1e293b;
            font-size: 18px;
        }
        .cta-button {
            display: inline-block;
            background: #3b82f6;
            color: white;
            padding: 12px 24px;
            text-decoration: none;
            border-radius: 6px;
            font-weight: 500;
            margin: 20px 0;
        }
        .footer {
            background: #f8fafc;
            padding: 20px 30px;
            border-top: 1px solid #e2e8f0;
            text-align: center;
            font-size: 14px;
            color: #64748b;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📊 Weekly Security Report</h1>
            <p>{{ $domain->domain }} • {{ $weekStart->format('M j') }} - {{ $weekEnd->format('M j, Y') }}</p>
        </div>

        <div class="content">
            <p>Hello {{ $domain->user->name }},</p>

            <p>Here's your weekly security summary for <strong>{{ $domain->domain }}</strong>. We've attached a detailed PDF report with comprehensive analysis and recommendations.</p>

            <div class="summary-box">
                <h3>📈 This Week's Highlights</h3>
                <p>Your domain monitoring has been active this week. Check the attached PDF report for detailed insights including:</p>
                <ul>
                    <li>Security scan results and trends</li>
                    <li>DNS record status and changes</li>
                    <li>Blacklist monitoring updates</li>
                    <li>Incident alerts and resolutions</li>
                    <li>Recommendations for improvements</li>
                </ul>
            </div>

            <p>Want to dive deeper into your domain's security posture?</p>

            <a href="{{ url('/domains/' . $domain->id) }}" class="cta-button">
                View Domain Dashboard
            </a>

            <p>The attached PDF contains your complete weekly analysis. If you have any questions about the findings or need assistance with implementing our recommendations, please don't hesitate to reach out.</p>

            <p>Stay secure,<br>
            <strong>The MXScan Team</strong></p>
        </div>

        <div class="footer">
            <p>This report was automatically generated by MXScan's monitoring system.</p>
            <p>To manage your notification preferences, visit your <a href="{{ url('/settings/notifications') }}">account settings</a>.</p>
        </div>
    </div>
</body>
</html>
